version: '3.8'

services:
  moon-cx:
    container_name: moon-cx
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - moon-cx-network

networks:
  moon-cx-network:
    driver: bridge
